modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="death_flower"
version="1.0.0"
displayName="Death Flower"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/BullfrogMods/minecraft-death-flower-mod"
authors="jeremiah, MCreator"

[[dependencies.death_flower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




